# Generated by Django 4.2.5 on 2024-01-16 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ps_calendar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Required', max_length=255, verbose_name='Project Title')),
                ('subheadline', models.CharField(blank=True, max_length=255, verbose_name='Subheadline')),
                ('artists', models.CharField(help_text='Required', max_length=255, verbose_name='Artist(s)')),
                ('curators', models.CharField(help_text='Required', max_length=255, verbose_name='Curator(s)')),
                ('location', models.CharField(help_text='Required', max_length=255, verbose_name='Location')),
                ('link_to_location', models.URLField(blank=True, verbose_name='Link to Location')),
                ('location_address', models.TextField(help_text='Required', verbose_name='Location Address')),
                ('exhibition_opening', models.DateField(help_text='Required', verbose_name='Exhibition Opening')),
                ('exhibition_end', models.DateField(help_text='Required', verbose_name='Exhibition End')),
                ('description', models.TextField(help_text='Required', verbose_name='Text/Description')),
                ('social_media_info', models.TextField(blank=True, verbose_name='Social Media Info')),
                ('email', models.EmailField(help_text='Required', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='E-mail')),
                ('consent_to_collect_info', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required', verbose_name='I consent to having x collect the submitted names, information, and e-mail!')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ps_calendar.models.get_image_filename, verbose_name='Calender Image')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ps_calendar.calendarsubmission')),
            ],
        ),
    ]
