# Generated by Django 4.2.5 on 2024-01-16 07:13

from django.db import migrations, models
import ps_calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarimages',
            name='caption',
            field=models.TextField(default=None, help_text='Caption for the image', verbose_name='Caption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarimages',
            name='image',
            field=models.ImageField(upload_to=ps_calendar.models.get_image_filename, validators=[ps_calendar.models.validate_image_size, ps_calendar.models.validate_image_extension], verbose_name='Calender Image'),
        ),
    ]
