# Generated by Django 4.2.5 on 2024-01-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0004_alter_calendarimages_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarimages',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='Image Caption'),
        ),
    ]
