# Generated by Django 4.2.5 on 2024-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0005_alter_calendarimages_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubmission',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Check this box to highlight'),
        ),
    ]
