# Generated by Django 4.2.5 on 2024-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0006_calendarsubmission_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
