# Generated by Django 4.2.9 on 2024-01-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0007_calendarsubmission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsubmission',
            name='subheadline',
        ),
        migrations.AddField(
            model_name='calendarsubmission',
            name='published',
            field=models.BooleanField(default=False, help_text='Check this box to publish'),
        ),
        migrations.AddField(
            model_name='calendarsubmission',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='artists',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Artist(s)'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='consent_to_collect_info',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required *', verbose_name='Do you consent to having collected the submitted names, information, and e-mail?'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='curators',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Curator(s)'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='description',
            field=models.TextField(help_text='Required *', verbose_name='Text/Description/Press Release'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='eg. 2024-01-02 Required *', verbose_name='Exhibition End'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='eg. 2024-01-01 Required *', verbose_name='Exhibition Opening'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='location',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='location_address',
            field=models.TextField(help_text='Required *<br/><br/>Format:<br/>[street name] [street number], [town/city], [postcode], Denmark<br/><br/>Example:<br/>Halmtorvet 11D, København V, 1700, Denmark', verbose_name='Location Address'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='project_title',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Title'),
        ),
    ]
