# Generated by Django 4.2.9 on 2024-01-24 17:09

from django.db import migrations, models
import ps_calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0008_remove_calendarsubmission_subheadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarimages',
            name='image',
            field=models.ImageField(upload_to=ps_calendar.models.get_image_filename, validators=[ps_calendar.models.validate_image_size, ps_calendar.models.validate_image_extension], verbose_name='Event Image'),
        ),
    ]
