# Generated by Django 4.2.7 on 2024-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0010_calendarsubmission_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='admission',
            field=models.CharField(help_text='Required *<br/><br/>Format:<br/>[value] [valuta] or free<br/><br/>Examples:<br/>- 80 DKK<br/>- Free', max_length=255, null=True, verbose_name='Admission'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='opening_hours',
            field=models.TextField(help_text='Required *<br/><br/>Format:<br/>[weekday(s) and interval]: [timeslot]<br/><br/>Examples:<br/>- Wednesday-Saturday, except Thursday: 16:00-20:00<br/>- Thursday, Friday: 19:00-22:00<br/>- By appointment, Saturday: 12:00-16:00<br/>- Wednesday-Friday: 16:00-20:00,<br/>  Saturday: 12:00-17:00,<br/>  Sunday: 12:00-14:00,<br/>  Closed from 30.12.23 until 06.01.24', null=True, verbose_name='Opening Hours'),
        ),
    ]
