# Generated by Django 4.2.7 on 2024-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0011_alter_calendarsubmission_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubmission',
            name='event_type',
            field=models.CharField(choices=[('Exhibition', 'Exhibition'), ('Performance', 'Performance'), ('Screening', 'Screening'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Type'),
        ),
    ]
