# Generated by Django 4.2.7 on 2024-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0013_calendarsubmission_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='location_address',
            field=models.CharField(help_text='Required *<br/><br/>Format:<br/>[street name] [street number], [town/city], [postcode], Denmark<br/><br/>Example:<br/>Halmtorvet 11D, København V, 1700, Denmark', max_length=1000, null=True, verbose_name='Location Address'),
        ),
    ]
