# Generated by Django 4.2.9 on 2024-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0015_alter_calendarsubmission_link_to_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='artists',
            field=models.CharField(help_text='Required *<br/><br/>Divide multiple artists with comma (,)', max_length=255, verbose_name='Artist(s)'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='curators',
            field=models.CharField(help_text='Required *<br/><br/>Divide multiple curators with comma (,)', max_length=255, verbose_name='Curator(s)'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='Required*<br/><br/>e.g., 16/10/2023', verbose_name='Exhibition End'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='Required*<br/><br/>e.g., 14/10/2023', verbose_name='Exhibition Opening'),
        ),
    ]
