# Generated by Django 4.2.9 on 2024-03-01 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0016_alter_calendarsubmission_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubmission',
            name='opening',
            field=models.DateField(help_text='Required *<br/><br/>e.g., 13/10/2023', null=True, verbose_name='Opening/vernissage date'),
        ),
        migrations.AddField(
            model_name='calendarsubmission',
            name='opening_hours_for_opening_date',
            field=models.TextField(help_text='Required *<br/><br/>Format:<br/>[timeslot]<br/><br/>Examples:<br/>- 17:00-20:00', null=True, verbose_name='Opening hours for opening/vernissage'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='email',
            field=models.EmailField(help_text='Required *', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='Required *<br/><br/>e.g., 16/10/2023', verbose_name='Activity end date'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='Required *<br/><br/>e.g., 14/10/2023', verbose_name='Activity start date'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='location_address',
            field=models.CharField(help_text='Required *<br/><br/>Format:<br/>[street name] [street number], [town/city], [postcode], Denmark<br/><br/>Example:<br/>Halmtorvet 11D, København V, 1700, Denmark', max_length=1000, null=True, verbose_name='Location address'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='opening_hours',
            field=models.TextField(help_text='Required *<br/><br/>Format:<br/>[weekday(s) and interval]: [timeslot]<br/><br/>Examples:<br/>- Wednesday-Saturday, except Thursday: 16:00-20:00<br/>- Thursday, Friday: 19:00-22:00<br/>- By appointment, Saturday: 12:00-16:00<br/>- Wednesday-Friday: 16:00-20:00,<br/>  Saturday: 12:00-17:00,<br/>  Sunday: 12:00-14:00,<br/>  Closed from 30.12.23 until 06.01.24', null=True, verbose_name='Weekly opening hours'),
        ),
    ]
