# Generated by Django 4.2.9 on 2024-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0017_calendarsubmission_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='opening_hours_for_opening_date',
            field=models.CharField(help_text='Required *<br/><br/>Format:<br/>[timeslot]<br/><br/>Examples:<br/>- 17:00-20:00', max_length=255, null=True, verbose_name='Opening hours for opening/vernissage'),
        ),
    ]
