# Generated by Django 4.2.10 on 2024-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0019_alter_calendarsubmission_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='curators',
            field=models.CharField(blank=True, help_text='Divide multiple curators with comma (,)', max_length=255, verbose_name='Curator(s)'),
        ),
    ]
