# Generated by Django 4.2.9 on 2024-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0020_alter_calendarsubmission_curators'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubmission',
            name='one_day_event',
            field=models.BooleanField(default=False),
        ),
    ]
