# Generated by Django 4.2.9 on 2024-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0021_calendarsubmission_one_day_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_end',
            field=models.DateField(blank=True, help_text='Required *<br/><br/>e.g., 16/10/2023', null=True, verbose_name='Activity end date'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='exhibition_opening',
            field=models.DateField(blank=True, help_text='Required *<br/><br/>e.g., 14/10/2023', null=True, verbose_name='Activity start date'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='one_day_event',
            field=models.BooleanField(default=False, help_text='<br/>Check this box if the event is not on for multiple days', verbose_name='One-day event'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Required *<br/><br/>Format:<br/>[weekday(s) and interval]: [timeslot]<br/><br/>Examples:<br/>- Wednesday-Saturday, except Thursday: 16:00-20:00<br/>- Thursday, Friday: 19:00-22:00<br/>- By appointment, Saturday: 12:00-16:00<br/>- Wednesday-Friday: 16:00-20:00,<br/>  Saturday: 12:00-17:00,<br/>  Sunday: 12:00-14:00,<br/>  Closed from 30.12.23 until 06.01.24', null=True, verbose_name='Weekly opening hours'),
        ),
    ]
