# Generated by Django 4.2.9 on 2024-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_calendar', '0022_alter_calendarsubmission_exhibition_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubmission',
            name='event_type',
            field=models.CharField(choices=[('Exhibition', 'Exhibition'), ('Performance', 'Performance'), ('Workshop', 'Workshop'), ('Screening', 'Screening'), ('Release', 'Release'), ('Talk', 'Talk'), ('Fundraiser', 'Fundraiser'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Type'),
        ),
    ]
