# Generated by Django 4.2.9 on 2024-09-08 08:12

from django.db import migrations, models
import ps_calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ("ps_calendar", "0023_alter_calendarsubmission_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarimages",
            name="image",
            field=models.ImageField(
                help_text="Optional. Max uploaded size is 3 MB.<br/><br/>",
                upload_to=ps_calendar.models.get_image_filename,
                validators=[
                    ps_calendar.models.validate_image_size,
                    ps_calendar.models.validate_image_extension,
                ],
                verbose_name="Event Image",
            ),
        ),
        migrations.AlterField(
            model_name="calendarsubmission",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Exhibition", "Exhibition"),
                    ("Performance", "Performance"),
                    ("Workshop", "Workshop"),
                    ("Screening", "Screening"),
                    ("Release", "Release"),
                    ("Talk", "Talk"),
                    ("Walk", "Walk"),
                    ("Fundraiser", "Fundraiser"),
                    ("Other", "Other"),
                ],
                default="Exhibition",
                help_text="Required *",
                max_length=500,
                verbose_name="Type",
            ),
        ),
    ]
