# Generated by Django 4.2.9 on 2024-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required *', max_length=255, verbose_name='Title')),
                ('category', models.CharField(choices=[('Open call', 'Open call'), ('News', 'News'), ('Course and education', 'Courses and education'), ('Event', 'Event'), ('Residency', 'Residency'), ('Job', 'Job'), ('Funding or grant', 'Funding or grant'), ('Atelier/studio', 'Atelier/studio'), ('Trade (buying/selling)', 'Trade (buying/selling)'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Category')),
                ('location', models.CharField(help_text='Required *. E.g. city name or region', max_length=255, verbose_name='Location')),
                ('description', models.TextField(help_text='Required *', verbose_name='Description')),
                ('contact_information', models.TextField(help_text='Required *. E.g., phone number or/and e-mail. Be aware this will be exposed on the pinboard', verbose_name='Preferred contact information')),
                ('consent_to_collect_info', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required *', verbose_name='Do you consent to having collected and exposing the submitted contact information?')),
                ('published', models.BooleanField(default=False, help_text='Check this box to publish')),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
    ]
