# Generated by Django 4.2.9 on 2024-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0002_remove_pinboard_slug_alter_pinboard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='category',
            field=models.CharField(choices=[('Open call', 'opencall'), ('News', 'news'), ('Course and education', 'education'), ('Residency', 'recidency'), ('Job', 'job'), ('Funding or grant', 'funding'), ('Atelier/studio', 'studio'), ('Trade (buying/selling)', 'trade'), ('Other', 'other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Category'),
        ),
    ]
