# Generated by Django 4.2.9 on 2024-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0004_alter_pinboard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pinboard',
            name='category',
            field=models.CharField(choices=[('Open call', 'Open call'), ('News', 'News'), ('Course and education', 'Courses and education'), ('Residency', 'Residency'), ('Job', 'Job'), ('Funding or grant', 'Funding or grant'), ('Atelier/studio', 'Atelier/studio'), ('Trade (buying/selling)', 'Trade (buying/selling)'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Category'),
        ),
    ]
