# Generated by Django 4.2.9 on 2024-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0005_pinboard_slug_alter_pinboard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='category',
            field=models.CharField(choices=[('Open call', 'Open call'), ('News', 'News'), ('education', 'Courses and education'), ('Residency', 'Residency'), ('Job', 'Job'), ('Funding or grant', 'Funding or grant'), ('Atelier/studio', 'Atelier/studio'), ('Trade (buying/selling)', 'Trade (buying/selling)'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Category'),
        ),
    ]
