# Generated by Django 4.2.9 on 2024-03-26 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0009_alter_pinboard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
