# Generated by Django 4.2.9 on 2024-03-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0010_pinboard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
