# Generated by Django 4.2.9 on 2024-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0011_alter_pinboard_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboard',
            name='expiration_date',
            field=models.DateField(help_text='Required *<br/><br/>The post will be removed after the expiration date.<br/><br/>e.g., 14/10/2023', null=True, verbose_name='Expiration date'),
        ),
    ]
