# Generated by Django 4.2.9 on 2024-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_pinboard', '0013_alter_pinboard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
