# Generated by Django 4.2.9 on 2024-09-08 08:12

from django.db import migrations, models
import django.db.models.deletion
import ps_pinboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("ps_pinboard", "0015_alter_pinboard_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinboardImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Optional. Upload max filesize: 3 MB.<br/>",
                        upload_to=ps_pinboard.models.get_image_filename,
                        validators=[
                            ps_pinboard.models.validate_image_size,
                            ps_pinboard.models.validate_image_extension,
                        ],
                        verbose_name="Post Image",
                    ),
                ),
                (
                    "pinboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ps_pinboard.pinboard",
                    ),
                ),
            ],
        ),
    ]
