# Generated by Django 4.2.9 on 2024-01-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Required', max_length=255, verbose_name='Project Title')),
                ('subheadline', models.TextField(blank=True, verbose_name='Subheadline')),
                ('artists', models.CharField(help_text='Required', max_length=255, verbose_name='Artist(s)')),
                ('curators', models.CharField(help_text='Required', max_length=255, verbose_name='Curator(s)')),
                ('location', models.CharField(help_text='Required', max_length=255, verbose_name='Location')),
                ('link_to_location', models.URLField(blank=True, verbose_name='Link to Location')),
                ('exhibition_opening', models.DateField(help_text='Required', verbose_name='Exhibition Opening')),
                ('exhibition_end', models.DateField(help_text='Required', verbose_name='Exhibition End')),
                ('description', models.TextField(help_text='Required', verbose_name='Text/Description')),
                ('text_author', models.CharField(help_text='Required', max_length=255, verbose_name='Text Author')),
                ('photographer', models.CharField(help_text='Required', max_length=255, verbose_name='Photographer')),
                ('link_to_video', models.URLField(blank=True, verbose_name='Link to Video')),
                ('images', models.ImageField(help_text='At least 5 images required', upload_to='exhibition_images/', verbose_name='Images')),
                ('social_media_info', models.TextField(blank=True, verbose_name='Social Media Info')),
                ('email', models.EmailField(help_text='Required', max_length=254, verbose_name='E-mail')),
                ('consent_to_collect_info', models.BooleanField(help_text='Required', verbose_name='I consent to having x collect the submitted names, information, and e-mail!')),
            ],
        ),
    ]
