# Generated by Django 4.2.9 on 2024-01-13 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ps_submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionsubmission',
            name='images',
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='consent_to_collect_info',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required', verbose_name='I consent to having x collect the submitted names, information, and e-mail!'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='email',
            field=models.EmailField(help_text='Required', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subheadline'),
        ),
        migrations.CreateModel(
            name='ExhibitionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ps_submission.models.get_image_filename, verbose_name='Exhibition Image')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ps_submission.exhibitionsubmission')),
            ],
        ),
    ]
