# Generated by Django 4.2.5 on 2024-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0003_alter_exhibitionimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionimages',
            name='caption',
            field=models.TextField(default='', help_text='Caption for the image', verbose_name='Caption'),
            preserve_default=False,
        ),
    ]
