# Generated by Django 4.2.5 on 2024-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0004_exhibitionimages_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimages',
            name='caption',
            field=models.CharField(help_text='Caption for the image', max_length=255, verbose_name='Caption'),
        ),
    ]
