# Generated by Django 4.2.5 on 2024-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0006_alter_exhibitionimages_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Check this box to highlight'),
        ),
    ]
