# Generated by Django 4.2.5 on 2024-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0007_exhibitionsubmission_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
