# Generated by Django 4.2.9 on 2024-01-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0008_exhibitionsubmission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='published',
            field=models.BooleanField(default=False, help_text='Check this box to publish'),
        ),
    ]
