# Generated by Django 4.2.9 on 2024-01-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0009_exhibitionsubmission_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='artists',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Artist(s)'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='consent_to_collect_info',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required *', verbose_name='I consent to having collected the submitted names, information, and e-mail.'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='curators',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Curator(s)'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='description',
            field=models.TextField(help_text='Required *', verbose_name='Text/Description'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='email',
            field=models.EmailField(help_text='Required *', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='eg. 2024-01-02 Required *', verbose_name='Exhibition End'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='eg. 2024-01-01  Required *', verbose_name='Exhibition Opening'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='location',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='photographer',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Photographer'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='project_title',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='text_author',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Text Author'),
        ),
    ]
