# Generated by Django 4.2.9 on 2024-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0010_alter_exhibitionsubmission_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='consent_to_collect_info',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Required *', verbose_name='Do you consent to having collected the submitted names, information, and e-mail?'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='e.g., 16/10/2023<br/>Required *', verbose_name='Exhibition End'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='e.g., 14/10/2023<br/>Required *', verbose_name='Exhibition Opening'),
        ),
    ]
