# Generated by Django 4.2.9 on 2024-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0011_alter_exhibitionsubmission_consent_to_collect_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='event_type',
            field=models.CharField(choices=[('Exhibition', 'Exhibition'), ('Performance', 'Performance'), ('Screening', 'Screening'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Type'),
        ),
    ]
