# Generated by Django 4.2.9 on 2024-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0012_exhibitionsubmission_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionsubmission',
            name='subheadline',
        ),
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='project_title',
            field=models.CharField(help_text='Required *', max_length=255, verbose_name='Title'),
        ),
    ]
