# Generated by Django 4.2.9 on 2024-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0013_remove_exhibitionsubmission_subheadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='description',
            field=models.TextField(help_text='Required *', verbose_name='Text'),
        ),
    ]
