# Generated by Django 4.2.7 on 2024-01-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0014_alter_exhibitionsubmission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='description',
            field=models.TextField(help_text='Required *', verbose_name='Text/Description/Press Release'),
        ),
    ]
