# Generated by Django 4.2.7 on 2024-01-25 10:56

from django.db import migrations, models
import ps_submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0015_alter_exhibitionsubmission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimages',
            name='caption',
            field=models.CharField(help_text='Caption for the image', max_length=1000, verbose_name='Image Caption'),
        ),
        migrations.AlterField(
            model_name='exhibitionimages',
            name='image',
            field=models.ImageField(max_length=500, upload_to=ps_submission.models.get_image_filename, validators=[ps_submission.models.validate_image_size, ps_submission.models.validate_image_extension], verbose_name='Exhibition Image'),
        ),
    ]
