# Generated by Django 4.2.9 on 2024-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0018_alter_exhibitionsubmission_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionimages',
            name='cover_image',
            field=models.BooleanField(default=False, help_text='Check this box to set as cover image'),
        ),
    ]
