# Generated by Django 4.2.9 on 2024-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0020_alter_exhibitionsubmission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='event_type',
            field=models.CharField(choices=[('Exhibition', 'Exhibition'), ('Performance', 'Performance'), ('Screening', 'Screening'), ('Fundraiser', 'Fundraiser'), ('Other', 'Other')], default='Exhibition', help_text='Required *', max_length=500, verbose_name='Type'),
        ),
    ]
