# Generated by Django 4.2.9 on 2024-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0021_alter_exhibitionsubmission_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='artists',
            field=models.CharField(help_text='Required *<br/><br/>Divide multiple artists with comma (,)', max_length=2500, verbose_name='Artist(s)'),
        ),
    ]
