# Generated by Django 4.2.9 on 2024-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0022_alter_exhibitionsubmission_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='artists',
            field=models.TextField(help_text='Required *<br/><br/>Divide multiple artists with comma (,)', verbose_name='Artist(s)'),
        ),
    ]
