# Generated by Django 4.2.9 on 2024-04-13 15:27

from django.db import migrations, models
import ps_submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0023_alter_exhibitionsubmission_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimages',
            name='image',
            field=models.ImageField(max_length=500, upload_to=ps_submission.models.get_image_filename, validators=[ps_submission.models.validate_image_size, ps_submission.models.validate_image_extension], verbose_name='Activity Image'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_end',
            field=models.DateField(help_text='Required*<br/><br/>e.g., 16/10/2023', verbose_name='Activity end'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='exhibition_opening',
            field=models.DateField(help_text='Required*<br/><br/>e.g., 14/10/2023', verbose_name='Activity opening'),
        ),
    ]
