# Generated by Django 4.2.9 on 2024-05-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0026_alter_exhibitionsubmission_curators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimages',
            name='cover_image',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box to set as cover image'),
        ),
        migrations.AlterField(
            model_name='exhibitionimages',
            name='exhibition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ps_submission.exhibitionsubmission'),
        ),
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='photographer',
            field=models.CharField(help_text='Required *<br/><br/>Divide multiple photographers with comma (,)', max_length=255, verbose_name='Photographer'),
        ),
    ]
