# Generated by Django 4.2.9 on 2024-07-07 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_submission', '0029_alter_exhibitionsubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionsubmission',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 7, 13, 28, 11, 301938, tzinfo=datetime.timezone.utc), verbose_name='Created'),
        ),
    ]
